name: Deploy Application Deployment
on:
  workflow_dispatch:
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ '17' ]  # Specify the Java version

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenJDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'  # 'temurin' is the recommended OpenJDK distribution

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests with test profile
        run: mvn test -Dspring.profiles.active=test
      - name: Install dependencies and test
        run: mvn clean install
      - name: Package application
        run: mvn package -DskipTests=true
      - name: Archive the artifact
        uses: actions/upload-artifact@v3
        with:
          name: configserver
          path: target/*.jar

  Containerize:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: AWS ECR Login
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}  # Set the AWS region

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: configserver
          path: ./target  # Specify the path to download the artifact

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/configserver:latest
